- name: Creating a user called {{ username }}
  user: 
    name: "{{ username }}"
    password: "{{ password_hash }}"
    state: present
    shell: /bin/bash
    groups: wheel
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa


- name: Copy public key to the remote box for user {{ username }}
  become: true
  copy: 
    src: "{{ public_key_path }}" 
    dest: /home/{{ username }}/.ssh/authorized_keys
    mode: 0600
    owner: "{{ username }}"
    group: "{{ username }}"


- name: Add user to sudoers 
  lineinfile:
    dest: /etc/sudoers
    regexp: "{{ username }} ALL"
    line: "{{ username }}	ALL=(ALL) 	NOPASSWD: ALL"
    state: present

